version: '3.8'
services:
    postgres:
        image: postgres:latest
        ports:
            - '1234:5432'
        environment:
            POSTGRES_USER: nestjs
            POSTGRES_PASSWORD: nestjs
            POSTGRES_DB: nestjs
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
